import type { LiveSourceDefinition } from "./registry";

const DVIDS_HOSTS = ["www.dvidshub.net", "dvidshub.net"] as const;
const NASA_HOSTS = ["www.nasa.gov", "nasa.gov", "plus.nasa.gov"] as const;
const NPS_HOSTS = ["www.nps.gov", "home.nps.gov"] as const;
const NIH_HOSTS = ["videocast.nih.gov", "www.nih.gov", "nih.gov"] as const;
const FDA_HOSTS = ["www.fda.gov", "fda.gov"] as const;
const SEC_HOSTS = ["www.sec.gov", "sec.gov"] as const;
const FCC_HOSTS = ["www.fcc.gov", "fcc.gov"] as const;
const EU_AV_HOSTS = ["audiovisual.ec.europa.eu", "ec.europa.eu", "commission.europa.eu"] as const;
const HOUSE_HOSTS = ["live.house.gov", "www.house.gov", "house.gov"] as const;
const SENATE_HOSTS = ["www.senate.gov", "senate.gov"] as const;

function officialLink(
  key: string,
  title: string,
  titleUrdu: string,
  description: string,
  provider: LiveSourceDefinition["provider"],
  officialSourceUrl: string,
  termsUrl: string,
  attribution: string,
  allowedHosts: readonly string[],
): LiveSourceDefinition {
  return {
    key,
    slug: key,
    title,
    titleUrdu,
    description,
    provider,
    adapter: "official_live_link",
    officialSourceUrl,
    termsUrl,
    attribution,
    allowedHosts,
    refreshIntervalSeconds: 900,
    freshnessThresholdSeconds: 86400,
    offAirAllowed: true,
  };
}

function npsCamera(
  key: string,
  title: string,
  titleUrdu: string,
  description: string,
  pageUrl: string,
): LiveSourceDefinition {
  return {
    key,
    slug: key,
    title,
    titleUrdu,
    description,
    provider: "nps",
    adapter: "public_domain_live_image",
    officialSourceUrl: pageUrl,
    termsUrl: "https://www.nps.gov/aboutus/disclaimer.htm",
    attribution: "Source: National Park Service. No claim to original U.S. Government works. NPS does not endorse Jalwa.",
    allowedHosts: NPS_HOSTS,
    imageUrl: pageUrl,
    imagePathPattern: "^/webcams-[a-z0-9-]+/[^?#]+\\.(?:jpe?g|png|webp|gif)$",
    refreshIntervalSeconds: 300,
    freshnessThresholdSeconds: 7200,
  };
}

export const OPEN_GOVERNMENT_LIVE_SOURCES = {
  "dvids-live-webcasts": officialLink(
    "dvids-live-webcasts",
    "DVIDS Live Webcasts",
    "ڈی وی آئی ڈی ایس براہ راست نشریات",
    "Upcoming official U.S. Department of Defense public-affairs webcasts. Individual events remain subject to their displayed rights metadata.",
    "dvids",
    "https://www.dvidshub.net/webcast",
    "https://www.dvidshub.net/about/copyright",
    "Source: Defense Visual Information Distribution Service. The U.S. Department of Defense does not endorse Jalwa.",
    DVIDS_HOSTS,
  ),
  "dvids-pentagon-press-briefings": officialLink(
    "dvids-pentagon-press-briefings",
    "Pentagon Press Briefings",
    "پینٹاگون پریس بریفنگز",
    "Official Pentagon press-briefing coverage published through DVIDS.",
    "dvids",
    "https://www.dvidshub.net/feature/PentagonPressBriefings",
    "https://www.dvidshub.net/about/copyright",
    "Source: Defense Visual Information Distribution Service. The U.S. Department of Defense does not endorse Jalwa.",
    DVIDS_HOSTS,
  ),
  "dvids-white-house-public-events": officialLink(
    "dvids-white-house-public-events",
    "White House Public Events via DVIDS",
    "وائٹ ہاؤس عوامی تقریبات بذریعہ ڈی وی آئی ڈی ایس",
    "Official public events made available through the DVIDS webcast catalogue.",
    "dvids",
    "https://www.dvidshub.net/webcast",
    "https://www.dvidshub.net/about/copyright",
    "Source: Defense Visual Information Distribution Service. No endorsement of Jalwa is implied.",
    DVIDS_HOSTS,
  ),
  "dvids-navy-recruit-graduations": officialLink(
    "dvids-navy-recruit-graduations",
    "U.S. Navy Recruit Training Graduations",
    "امریکی بحریہ ریکروٹ ٹریننگ گریجویشن",
    "Official recruit-training graduation webcasts listed by DVIDS.",
    "dvids",
    "https://www.dvidshub.net/webcast",
    "https://www.dvidshub.net/about/copyright",
    "Source: Defense Visual Information Distribution Service. The U.S. Navy does not endorse Jalwa.",
    DVIDS_HOSTS,
  ),
  "dvids-defense-conferences-ceremonies": officialLink(
    "dvids-defense-conferences-ceremonies",
    "Defense Conferences and Ceremonies",
    "دفاعی کانفرنسیں اور تقریبات",
    "Official defense conferences, ceremonies and public-affairs events listed by DVIDS.",
    "dvids",
    "https://www.dvidshub.net/webcast",
    "https://www.dvidshub.net/about/copyright",
    "Source: Defense Visual Information Distribution Service. The U.S. Department of Defense does not endorse Jalwa.",
    DVIDS_HOSTS,
  ),

  "nasa-plus-live-events": officialLink(
    "nasa-plus-live-events",
    "NASA+ Live Events",
    "ناسا پلس براہ راست تقریبات",
    "Official NASA+ live and upcoming event schedule.",
    "nasa",
    "https://plus.nasa.gov/scheduled-events/",
    "https://www.nasa.gov/nasa-brand-center/images-and-media/",
    "Source: NASA. NASA does not endorse Jalwa or its advertisers.",
    NASA_HOSTS,
  ),
  "nasa-mission-launch-coverage": officialLink(
    "nasa-mission-launch-coverage",
    "NASA Mission and Launch Coverage",
    "ناسا مشن اور لانچ کوریج",
    "Official NASA mission, launch and agency-event coverage.",
    "nasa",
    "https://www.nasa.gov/live/",
    "https://www.nasa.gov/nasa-brand-center/images-and-media/",
    "Source: NASA. NASA does not endorse Jalwa or its advertisers.",
    NASA_HOSTS,
  ),
  "nasa-space-to-ground": officialLink(
    "nasa-space-to-ground",
    "NASA Space-to-Ground",
    "ناسا اسپیس ٹو گراؤنڈ",
    "Official NASA space-station news, mission audio and scheduled coverage.",
    "nasa",
    "https://plus.nasa.gov/topics/news-events/",
    "https://www.nasa.gov/nasa-brand-center/images-and-media/",
    "Source: NASA. NASA does not endorse Jalwa or its advertisers.",
    NASA_HOSTS,
  ),

  "nps-devils-tower-entrance": npsCamera(
    "nps-devils-tower-entrance",
    "NPS Devils Tower Entrance",
    "نیشنل پارک سروس ڈیولز ٹاور داخلی منظر",
    "Current official National Park Service view near the Devils Tower entrance.",
    "https://www.nps.gov/media/webcam/view.htm?id=353840EE-9D49-67A6-C3D2292B5251E4DD",
  ),
  "nps-mount-rainier-sunrise": npsCamera(
    "nps-mount-rainier-sunrise",
    "NPS Mount Rainier Sunrise",
    "ماؤنٹ رینیئر سن رائز منظر",
    "Current official National Park Service view from Sunrise at Mount Rainier.",
    "https://www.nps.gov/media/webcam/view.htm?id=81B462EC-1DD8-B71B-0B99F890C596FA16",
  ),
  "nps-mount-rainier-paradise": npsCamera(
    "nps-mount-rainier-paradise",
    "NPS Mount Rainier Paradise",
    "ماؤنٹ رینیئر پیراڈائز منظر",
    "Current official National Park Service mountain view from Paradise.",
    "https://www.nps.gov/media/webcam/view.htm?id=81B46307-1DD8-B71B-0B72918A4B2EB790",
  ),
  "nps-mount-rainier-tatoosh": npsCamera(
    "nps-mount-rainier-tatoosh",
    "NPS Mount Rainier Tatoosh Range",
    "ماؤنٹ رینیئر ٹیٹوش رینج",
    "Current official National Park Service view of the Tatoosh Range.",
    "https://www.nps.gov/media/webcam/view.htm?id=81B46402-1DD8-B71B-0B95C911C1395AAC",
  ),
  "nps-guadalupe-pine-springs": npsCamera(
    "nps-guadalupe-pine-springs",
    "NPS Guadalupe Pine Springs Canyon",
    "گواڈالوپ پائن اسپرنگز کینین",
    "Current official National Park Service view from Pine Springs Canyon.",
    "https://www.nps.gov/media/webcam/view.htm?id=E73E3175-DF46-3AF2-28593FC1F83AE264",
  ),
  "nps-guadalupe-el-capitan": npsCamera(
    "nps-guadalupe-el-capitan",
    "NPS Guadalupe El Capitan",
    "گواڈالوپ ایل کیپٹن منظر",
    "Current official National Park Service view of El Capitan.",
    "https://www.nps.gov/media/webcam/view.htm?id=9849DE2B-BC23-1110-33CED7C04E8AAF05",
  ),
  "nps-shenandoah-mountain-view": npsCamera(
    "nps-shenandoah-mountain-view",
    "NPS Shenandoah Mountain View",
    "شیننڈوا پہاڑی منظر",
    "Current official National Park Service mountain view in Shenandoah.",
    "https://www.nps.gov/media/webcam/view.htm?id=81B46B71-1DD8-B71B-0B55074571E08B1E",
  ),
  "nps-shenandoah-big-meadows": npsCamera(
    "nps-shenandoah-big-meadows",
    "NPS Shenandoah Big Meadows",
    "شیننڈوا بگ میڈوز",
    "Current official National Park Service view of Big Meadows.",
    "https://www.nps.gov/media/webcam/view.htm?id=81B46B99-1DD8-B71B-0B124A40CC3384CE",
  ),
  "nps-smokies-newfound-gap": npsCamera(
    "nps-smokies-newfound-gap",
    "NPS Great Smoky Mountains Newfound Gap",
    "گریٹ اسموکی ماؤنٹینز نیوفاؤنڈ گیپ",
    "Current official National Park Service view at Newfound Gap.",
    "https://www.nps.gov/media/webcam/view.htm?id=C589EEEF-1DD8-B71B-0B0463C308FF64DD",
  ),
  "nps-point-reyes-beach": npsCamera(
    "nps-point-reyes-beach",
    "NPS Point Reyes Beach",
    "پوائنٹ ریئس ساحلی منظر",
    "Current official National Park Service beach view at Point Reyes.",
    "https://www.nps.gov/media/webcam/view.htm?id=5A967BB2-CB78-43A7-1C861C4554D5D50D",
  ),
  "nps-yellowstone-electric-peak": npsCamera(
    "nps-yellowstone-electric-peak",
    "NPS Yellowstone Electric Peak",
    "ییلو اسٹون الیکٹرک پیک",
    "Current official National Park Service north-entrance and Electric Peak view.",
    "https://www.nps.gov/media/webcam/view.htm?id=81B468AB-1DD8-B71B-0BE84D8E8E0F1112",
  ),
  "nps-glacier-night-sky": npsCamera(
    "nps-glacier-night-sky",
    "NPS Glacier Night Sky",
    "گلیشیئر نائٹ اسکائی",
    "Current official National Park Service night-sky view in Glacier National Park.",
    "https://www.nps.gov/media/webcam/view.htm?id=D4BDFE7E-AC7F-D681-8A03C820E06CBA0A",
  ),
  "nps-bunker-hill-west": npsCamera(
    "nps-bunker-hill-west",
    "NPS Bunker Hill Monument West View",
    "بنکر ہل یادگار مغربی منظر",
    "Current official National Park Service westward view from Bunker Hill Monument.",
    "https://www.nps.gov/media/webcam/view.htm?id=B17835F2-AC01-8A62-F2F0EC85B33643D3",
  ),
  "nps-painted-desert-inn": npsCamera(
    "nps-painted-desert-inn",
    "NPS Painted Desert Inn",
    "پینٹڈ ڈیزرٹ اِن منظر",
    "Current official National Park Service view at Painted Desert Inn.",
    "https://www.nps.gov/media/webcam/view.htm?id=81B46C72-1DD8-B71B-0BDC8D1824EBB9A7",
  ),
  "nps-el-morro": npsCamera(
    "nps-el-morro",
    "NPS El Morro National Monument",
    "ایل مورو قومی یادگار",
    "Current official National Park Service view at El Morro National Monument.",
    "https://www.nps.gov/media/webcam/view.htm?id=81B46AD5-1DD8-B71B-0BFB3F36B5DDC6EF",
  ),

  "nih-videocast": officialLink(
    "nih-videocast",
    "NIH VideoCast",
    "این آئی ایچ ویڈیو کاسٹ",
    "Official National Institutes of Health live scientific events. Inline use remains event-specific because guest material may retain copyright.",
    "nih",
    "https://videocast.nih.gov/",
    "https://www.nlm.nih.gov/web_policies.html",
    "Source: National Institutes of Health. NIH does not endorse Jalwa.",
    NIH_HOSTS,
  ),
  "fda-advisory-committee-live": officialLink(
    "fda-advisory-committee-live",
    "FDA Advisory Committee Live",
    "ایف ڈی اے مشاورتی کمیٹی براہ راست",
    "Official U.S. Food and Drug Administration advisory-committee calendar and webcast access.",
    "fda",
    "https://www.fda.gov/advisory-committees/advisory-committee-calendar",
    "https://www.fda.gov/about-fda/about-website/website-policies",
    "Source: U.S. Food and Drug Administration. FDA does not endorse Jalwa.",
    FDA_HOSTS,
  ),
  "sec-public-meetings": officialLink(
    "sec-public-meetings",
    "SEC Public Meetings",
    "ایس ای سی عوامی اجلاس",
    "Official U.S. Securities and Exchange Commission public-meeting and event schedule.",
    "sec",
    "https://www.sec.gov/newsroom/meetings-events",
    "https://www.sec.gov/about/privacy-information",
    "Source: U.S. Securities and Exchange Commission. The SEC does not endorse Jalwa.",
    SEC_HOSTS,
  ),
  "fcc-open-meetings": officialLink(
    "fcc-open-meetings",
    "FCC Open Meetings and Workshops",
    "ایف سی سی کھلے اجلاس اور ورکشاپس",
    "Official Federal Communications Commission live meeting and workshop coverage.",
    "fcc",
    "https://www.fcc.gov/live",
    "https://www.fcc.gov/encyclopedia/website-policies-notices",
    "Source: Federal Communications Commission. The FCC does not endorse Jalwa.",
    FCC_HOSTS,
  ),
  "europe-by-satellite-ebs": officialLink(
    "europe-by-satellite-ebs",
    "Europe by Satellite — EbS",
    "یورپ بائی سیٹلائٹ ای بی ایس",
    "Official European Commission EbS live audiovisual service. Jalwa opens the official ad-free service and does not restream it.",
    "european_commission",
    "https://audiovisual.ec.europa.eu/en/ebs/live/1",
    "https://commission.europa.eu/legal-notice_en",
    "© European Union, 2026 — Source: European Commission Audiovisual Service. No endorsement of Jalwa is implied.",
    EU_AV_HOSTS,
  ),
  "europe-by-satellite-ebs-plus": officialLink(
    "europe-by-satellite-ebs-plus",
    "Europe by Satellite — EbS+",
    "یورپ بائی سیٹلائٹ ای بی ایس پلس",
    "Official European Commission EbS+ live audiovisual service. Jalwa opens the official ad-free service and does not restream it.",
    "european_commission",
    "https://audiovisual.ec.europa.eu/en/ebs/live/2",
    "https://commission.europa.eu/legal-notice_en",
    "© European Union, 2026 — Source: European Commission Audiovisual Service. No endorsement of Jalwa is implied.",
    EU_AV_HOSTS,
  ),
  "us-house-floorcast": officialLink(
    "us-house-floorcast",
    "U.S. House FloorCast",
    "امریکی ایوان نمائندگان فلور کاسٹ",
    "Official U.S. House floor proceedings. This entry is official-link only and must remain free of commercial sponsorship around the source.",
    "us_house",
    "https://live.house.gov/",
    "https://www.house.gov/website-information/content",
    "Source: U.S. House of Representatives. The House does not endorse Jalwa.",
    HOUSE_HOSTS,
  ),
  "us-senate-floor-webcast": officialLink(
    "us-senate-floor-webcast",
    "U.S. Senate Floor Webcast",
    "امریکی سینیٹ فلور ویب کاسٹ",
    "Official U.S. Senate floor webcast and daily proceedings schedule.",
    "us_senate",
    "https://www.senate.gov/floor/",
    "https://www.senate.gov/general/copyright.htm",
    "Source: United States Senate. The Senate does not endorse Jalwa.",
    SENATE_HOSTS,
  ),
} as const satisfies Record<string, LiveSourceDefinition>;

export type OpenGovernmentLiveSourceKey = keyof typeof OPEN_GOVERNMENT_LIVE_SOURCES;

export const OPEN_GOVERNMENT_TOP_LEVEL_KEYS = Object.keys(
  OPEN_GOVERNMENT_LIVE_SOURCES,
) as OpenGovernmentLiveSourceKey[];
