import pg from "pg";
const { Pool } = pg;
const IDENT = /^[A-Za-z_][A-Za-z0-9_]*$/;
const ROLES = new Set(["anon", "authenticated", "service_role"]);
function ident(v){ if(!IDENT.test(v)) throw new Error(`Unsafe SQL identifier: ${v}`); return `"${v}"`; }
function splitTopLevel(input){ const out=[]; let depth=0,start=0; for(let i=0;i<input.length;i++){ const c=input[i]; if(c==='(') depth++; else if(c===')') depth--; else if(c===','&&depth===0){out.push(input.slice(start,i).trim());start=i+1;} } const tail=input.slice(start).trim(); if(tail)out.push(tail); return out; }
function projection(input){ return splitTopLevel(input||'*').map(token=>{ const open=token.indexOf('('); if(open>0&&token.endsWith(')')){ const spec=token.slice(0,open).trim(); const [relation,hintRaw]=spec.split('!',2); return {kind:'relation',relation,hint:hintRaw||null,inner:hintRaw==='inner',fields:projection(token.slice(open+1,-1))}; } if(token==='*')return{kind:'star'}; const colon=token.indexOf(':'); return colon>0?{kind:'column',alias:token.slice(0,colon).trim(),column:token.slice(colon+1).trim()}:{kind:'column',alias:null,column:token.trim()}; }); }
function fail(error){ const e=error instanceof Error?error:new Error(String(error)); return {data:null,error:e}; }
export function createPool(connectionString,options={}){ return new Pool({connectionString,...options}); }
export class DatabaseClient{
  constructor(pool,options={}){ this.pool=pool; this.userId=options.userId??null; this.role=options.role??(this.userId?'authenticated':'anon'); this.auth=options.auth??{async getUser(){return{data:{user:null},error:null}},async signOut(){return{error:null}}}; this.relCache=new Map(); this.rpcCache=new Map(); }
  from(table){return new QueryBuilder(this,table);}
  async query(text,values=[]){return this.withContext(c=>c.query(text,values));}
  async withContext(fn){const c=await this.pool.connect();try{await c.query('begin');await c.query("select set_config('request.jwt.claim.sub',$1,true), set_config('request.jwt.claim.role',$2,true)",[this.userId??'',this.role]);if(ROLES.has(this.role))await c.query(`set local role ${ident(this.role)}`);const r=await fn(c);await c.query('commit');return r;}catch(e){await c.query('rollback').catch(()=>{});throw e;}finally{c.release();}}
  async rpc(name,args={}){try{if(!IDENT.test(name))throw new Error('Unsafe RPC name');const entries=Object.entries(args);const vals=[];const named=entries.map(([k,v])=>{if(!IDENT.test(k))throw new Error('Unsafe RPC parameter');vals.push(v);return `${ident(k)} => $${vals.length}`;});const meta=await this.rpcMeta(name);const r=await this.query(`select * from public.${ident(name)}(${named.join(',')})`,vals);if(meta?.returnsSet)return{data:r.rows,error:null};if(!r.rows.length)return{data:null,error:null};const row=r.rows[0],keys=Object.keys(row);return{data:keys.length===1?row[keys[0]]:row,error:null};}catch(e){return fail(e);}}
  async rpcMeta(name){if(this.rpcCache.has(name))return this.rpcCache.get(name);const r=await this.withContext(c=>c.query("select p.proretset from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname=$1 order by p.oid limit 1",[name]));const m=r.rows[0]?{returnsSet:Boolean(r.rows[0].proretset)}:null;this.rpcCache.set(name,m);return m;}
  async relationship(table,relation,hint){const key=`${table}:${relation}:${hint||''}`;if(this.relCache.has(key))return this.relCache.get(key);const constraintHint=hint&&hint!=='inner'?hint:null;const r=await this.withContext(c=>c.query(`select c.conname,src.relname source_table,sa.attname source_column,dst.relname target_table,da.attname target_column from pg_constraint c join pg_class src on src.oid=c.conrelid join pg_namespace sn on sn.oid=src.relnamespace join pg_class dst on dst.oid=c.confrelid join pg_namespace dn on dn.oid=dst.relnamespace join lateral unnest(c.conkey) with ordinality sk(attnum,ord) on true join lateral unnest(c.confkey) with ordinality dk(attnum,ord) on dk.ord=sk.ord join pg_attribute sa on sa.attrelid=src.oid and sa.attnum=sk.attnum join pg_attribute da on da.attrelid=dst.oid and da.attnum=dk.attnum where c.contype='f' and sn.nspname='public' and dn.nspname in ('public','auth') and ((src.relname=$1 and dst.relname=$2) or (src.relname=$2 and dst.relname=$1)) and ($3::text is null or c.conname=$3) order by c.conname,sk.ord`,[table,relation,constraintHint]));if(!r.rows.length)throw new Error(`No relationship between ${table} and ${relation}`);const x=r.rows[0];const rel=x.source_table===table?{kind:'one',currentColumn:x.source_column,relatedColumn:x.target_column}:{kind:'many',currentColumn:x.target_column,relatedColumn:x.source_column};this.relCache.set(key,rel);return rel;}
}
class QueryBuilder{
  constructor(db,table){if(!IDENT.test(table))throw new Error('Unsafe table');this.db=db;this.table=table;this.operation='select';this.selection='*';this.selectionOptions={};this.payload=null;this.upsertOptions={};this.filters=[];this.orders=[];this.take=null;this.skip=null;this.cardinality='many';}
  select(cols='*',opts={}){this.selection=cols;this.selectionOptions=opts||{};return this;}
  insert(v){this.operation='insert';this.payload=v;this.selection=null;return this;}
  update(v){this.operation='update';this.payload=v;this.selection=null;return this;}
  upsert(v,o={}){this.operation='upsert';this.payload=v;this.upsertOptions=o;this.selection=null;return this;}
  delete(){this.operation='delete';this.selection=null;return this;}
  eq(c,v){return this.cmp(c,'=',v)} neq(c,v){return this.cmp(c,'<>',v)} gt(c,v){return this.cmp(c,'>',v)} gte(c,v){return this.cmp(c,'>=',v)} lt(c,v){return this.cmp(c,'<',v)} lte(c,v){return this.cmp(c,'<=',v)} like(c,v){return this.cmp(c,'like',v)} ilike(c,v){return this.cmp(c,'ilike',v)}
  cmp(c,o,v){this.filters.push({kind:'cmp',column:c,operator:o,value:v});return this;}
  in(c,v){this.filters.push({kind:'in',column:c,value:v});return this;}
  is(c,v){this.filters.push({kind:'is',column:c,value:v});return this;}
  not(c,o,v){this.filters.push({kind:'not',column:c,operator:o,value:v});return this;}
  contains(c,v){this.filters.push({kind:'contains',column:c,value:v});return this;}
  match(obj){for(const [c,v] of Object.entries(obj||{}))this.eq(c,v);return this;}
  order(c,o={}){this.orders.push({column:c,ascending:o.ascending!==false});return this;}
  limit(v){this.take=Number(v);return this;}
  range(a,b){this.skip=Number(a);this.take=Number(b)-Number(a)+1;return this;}
  single(){this.cardinality='single';return this;}
  maybeSingle(){this.cardinality='maybeSingle';return this;}
  then(res,rej){return this.execute().then(res,rej);}
  where(vals,alias=null){const pre=alias?`${ident(alias)}.`:'';const parts=[];for(const f of this.filters){const col=`${pre}${ident(f.column)}`;if(f.kind==='cmp'){if(f.value===null&&(f.operator==='='||f.operator==='<>'))parts.push(`${col} is ${f.operator==='<>'?'not ':''}null`);else{vals.push(f.value);parts.push(`${col} ${f.operator} $${vals.length}`);}}else if(f.kind==='in'){const arr=Array.isArray(f.value)?f.value:[];if(!arr.length)parts.push('false');else{const ps=arr.map(v=>{vals.push(v);return`$${vals.length}`});parts.push(`${col} in (${ps.join(',')})`);}}else if(f.kind==='is'){if(f.value===null)parts.push(`${col} is null`);else parts.push(`${col} is ${f.value?'true':'false'}`);}else if(f.kind==='not'){if(f.operator==='is'&&f.value===null)parts.push(`${col} is not null`);else{vals.push(f.value);parts.push(`not (${col} ${f.operator} $${vals.length})`);}}else if(f.kind==='contains'){vals.push(JSON.stringify(f.value));parts.push(`${col} @> $${vals.length}::jsonb`);}}
    return parts.length?` where ${parts.join(' and ')}`:'';}
  async renderProjection(fields,table,alias,innerPredicates){const out=[];for(const f of fields){if(f.kind==='star'){out.push(`${ident(alias)}.*`);continue;}if(f.kind==='column'){const e=`${ident(alias)}.${ident(f.column)}`;out.push(f.alias?`${e} as ${ident(f.alias)}`:e);continue;}const rel=await this.db.relationship(table,f.relation,f.hint);const a=`r_${Math.random().toString(36).slice(2,8)}`;const childInner=[];const child=await this.renderProjection(f.fields,f.relation,a,childInner);const join=`${ident(a)}.${ident(rel.relatedColumn)}=${ident(alias)}.${ident(rel.currentColumn)}`;if(f.inner)innerPredicates.push(`exists (select 1 from public.${ident(f.relation)} ${ident(a)} where ${join})`);if(rel.kind==='one')out.push(`(select row_to_json(_r) from (select ${child} from public.${ident(f.relation)} ${ident(a)} where ${join}${childInner.length?' and '+childInner.join(' and '):''} limit 1) _r) as ${ident(f.relation)}`);else out.push(`(select coalesce(json_agg(_r),'[]'::json) from (select ${child} from public.${ident(f.relation)} ${ident(a)} where ${join}${childInner.length?' and '+childInner.join(' and '):''}) _r) as ${ident(f.relation)}`);}return out.join(', ')||`${ident(alias)}.*`;}
  shape(rows,count=null,mutationNoSelect=false){if(mutationNoSelect)return{data:null,error:null,...(count===null?{}:{count})};if(this.cardinality==='single'){if(rows.length!==1)return{data:null,error:new Error(`Expected one row, received ${rows.length}`)};return{data:rows[0],error:null,...(count===null?{}:{count})};}if(this.cardinality==='maybeSingle'){if(rows.length>1)return{data:null,error:new Error(`Expected zero or one row, received ${rows.length}`)};return{data:rows[0]??null,error:null,...(count===null?{}:{count})};}return{data:rows,error:null,...(count===null?{}:{count})};}
  returning(){if(!this.selection)return'';const fs=projection(this.selection).filter(f=>f.kind!=='relation');if(fs.some(f=>f.kind==='star'))return' returning *';const cols=fs.map(f=>`${ident(f.column)}${f.alias?` as ${ident(f.alias)}`:''}`);return` returning ${cols.join(',')||'*'}`;}
  async execute(){try{if(this.operation==='select'){const vals=[];const alias='t';const baseWhere=this.where(vals,alias);const inner=[];const proj=await this.renderProjection(projection(this.selection),this.table,alias,inner);const whereParts=[];if(baseWhere)whereParts.push(baseWhere.replace(/^ where /,''));whereParts.push(...inner);const where=whereParts.length?` where ${whereParts.join(' and ')}`:'';let count=null;if(this.selectionOptions.count==='exact'){const cr=await this.db.query(`select count(*)::bigint count from public.${ident(this.table)} ${ident(alias)}${where}`,vals);count=Number(cr.rows[0]?.count??0);if(this.selectionOptions.head)return{data:null,error:null,count};}let sql=`select ${proj} from public.${ident(this.table)} ${ident(alias)}${where}`;if(this.orders.length)sql+=` order by ${this.orders.map(x=>`${ident(alias)}.${ident(x.column)} ${x.ascending?'asc':'desc'}`).join(',')}`;if(Number.isFinite(this.take))sql+=` limit ${Math.max(0,Math.trunc(this.take))}`;if(Number.isFinite(this.skip))sql+=` offset ${Math.max(0,Math.trunc(this.skip))}`;const r=await this.db.query(sql,vals);return this.shape(r.rows,count);}if(this.operation==='insert'||this.operation==='upsert'){const rows=Array.isArray(this.payload)?this.payload:[this.payload];if(!rows.length||rows.some(r=>!r||typeof r!=='object'||Array.isArray(r)))throw new Error('Insert payload must contain objects');const cols=[...new Set(rows.flatMap(r=>Object.keys(r)))];const vals=[];const tuples=rows.map(r=>`(${cols.map(c=>{vals.push(r[c]??null);return`$${vals.length}`}).join(',')})`);let sql=`insert into public.${ident(this.table)} (${cols.map(ident).join(',')}) values ${tuples.join(',')}`;if(this.operation==='upsert'){const conflict=String(this.upsertOptions.onConflict??cols[0]).split(',').map(x=>x.trim()).filter(Boolean);const upd=cols.filter(c=>!conflict.includes(c));sql+=` on conflict (${conflict.map(ident).join(',')}) do ${upd.length?`update set ${upd.map(c=>`${ident(c)}=excluded.${ident(c)}`).join(',')}`:'nothing'}`;}sql+=this.returning();const r=await this.db.query(sql,vals);return this.shape(this.selection?r.rows:[],null,!this.selection);}if(this.operation==='update'){const entries=Object.entries(this.payload||{});if(!entries.length)throw new Error('Update payload has no columns');const vals=[];const sets=entries.map(([c,v])=>{vals.push(v);return`${ident(c)}=$${vals.length}`});let sql=`update public.${ident(this.table)} set ${sets.join(',')}${this.where(vals)}`+this.returning();const r=await this.db.query(sql,vals);return this.shape(this.selection?r.rows:[],null,!this.selection);}if(this.operation==='delete'){const vals=[];let sql=`delete from public.${ident(this.table)}${this.where(vals)}`+this.returning();const r=await this.db.query(sql,vals);return this.shape(this.selection?r.rows:[],null,!this.selection);}throw new Error('Unsupported database operation');}catch(e){return fail(e);}}
}
export function createDatabaseClient(pool,options={}){return new DatabaseClient(pool,options);}
